site_name: Valid Thought
site_url: https://www.validthought.de
repo_url: https://github.com/ValidThought/Page


theme:
  name: material
  custom_dir: material_customizations
  palette:
<<<<<<< Updated upstream
    primary: 'white'
    accent: 'white'
=======
    primary: 'cyan'
    accent: 'deep orange'
>>>>>>> Stashed changes
  language: 'en'
  feature:
    tabs: false
  search: false


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences

extra_javascript:
  - material_customizations/main.js
  - material_customizations/react-app.html
  - material_customizations/matrixslider.js
  - react-app/matrixslider.js

extra_css:
  - material_customizations/extra.css
  - material_customizations/matrixslider.css

nav: []
