site_name: Valid Thought
site_url: https://www.validthought.de
repo_url: https://github.com/ValidThought/Page


theme:
  name: material
  custom_dir: material_customizations
  palette:
    primary: 'white'
    accent: 'white'
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  generator: false

plugins: []

copyright: Copyright &copy; 2023 Jonathan Huber
